name: Test Successful Workflow Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Docker Build
        run: echo "Building Docker image..."

      - name: Simulate Docker Tag
        run: echo "Tagging Docker image..."

      - name: Simulate Docker Push
        run: echo "Pushing Docker image to ECR..."

      - name: Success Message
        run: echo "✅ Workflow completed successfully!"
